name: UltimateManHunt
main: com.icepaka89.UltimateManHunt.UltimateManHunt
version: 1.0.0
author: icepaka89
commands:
  assassin:
    description: Add a player to the assassins group
    usage: /<command> [player]
  speedrunner:
    description: Add a player to the speedrunners group
    usage: /<command> [player]
  randomize-spawn:
    description: Randomize the spawn location for all players
    usage: /<command>
  manhunt-groups:
    description: List players in both groups
    usage: /<command>
  starting-distance:
    description: Set starting distance (in blocks) assassins will start from speed runners
    usage: /<command> [distance]
  start-manhunt:
    description: Starts the manhunt! Teleports all players to starting positions
    usage: /<command>

