name: UltimateManHunt
main: com.icepaka89.UltimateManHunt.UltimateManHunt
version: 0.0.1
author: icepaka89
commands:
  assassin:
    description: Add a player to the assassins group
    usage: /<command> [player]

