name: UltimateManHunt
main: com.icepaka89.UltimateManHunt.UltimateManHunt
version: 1.0.0
author: icepaka89
commands:
  assassin:
    description: Add a player to the assassins group
    usage: /<command> [player]
  speedrunner:
    description: Add a player to the speedrunners group
    usage: /<command> [player]
  randomize-spawn:
    description: Randomize the spawn location for all players
    usage: /<command>
  manhunt-groups:
    description: List players in both groups
    usage: /<command>
  reset-manhunt-groups:
    description: Clears all manhunt groups
    usage: /<command>
  starting-distance:
    description: Set starting distance (in blocks) assassins will start from speed runners
    usage: /<command> [distance]
  start-manhunt:
    description: Starts the manhunt! Teleports all players to starting positions
    usage: /<command>
  countdown-time:
    description: Sets the time for the countdown timer when the game starts
    usage: /<command> [time]
  debuff-assassin:
    description: Sets the percentage to debuff all assassin attacks (between 0 and 1)
    usage: /<command> [debuff]
  toggle-freeze-assassin:
    description: Enable/Disable freezing the assassin if a speedrunner sees them
    usage: /<command>
  toggle-distance-reporting:
    description: Enable/Disable reporting distance between assassins and speedrunners
    usage: /<command>

