name: UltimateManHunt
main: com.icepaka89.UltimateManHunt.UltimateManHunt
version: 1.0.0
author: icepaka89
commands:
  assassin:
    description: Add a player to the assassins group
    usage: /<command> [player]
  speedrunner:
    description: Add a player to the speedrunners group
    usage: /<command> [player]
  randomize-spawn:
    description: Randomize the spawn location for all players
    usage: /<command>
  groups:
    description: List players in both groups
    usage: /<command>

